# Generated by Django 5.0.2 on 2024-03-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('gooded_id', models.IntegerField()),
                ('admin_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MusicFollowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('music_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('contents', models.TextField(max_length=500)),
                ('music', models.CharField(max_length=100)),
                ('original_post_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('icon', models.URLField()),
                ('description', models.TextField(max_length=300)),
                ('spotify_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('opponent_id', models.IntegerField()),
            ],
        ),
    ]
