# Generated by Django 4.2.11 on 2024-03-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='spotify_premium',
            field=models.BooleanField(default=False),
        ),
    ]
