# Generated by Django 4.2.11 on 2024-03-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicfollowdata',
            name='album_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicfollowdata',
            name='artist_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicfollowdata',
            name='image',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicfollowdata',
            name='song_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
