# Generated by Django 5.0.2 on 2024-03-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0002_rename_music_postdata_music_id_postdata_album_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='original_post_id',
            field=models.IntegerField(null=True),
        ),
    ]
