# Generated by Django 4.2.11 on 2024-03-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNS', '0002_musicfollowdata_album_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='spotify_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
